jobs:
  create_release_tag:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up Maven Central Repository
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      id: staging
      name: Reset staging/main
      run: 'git checkout -B staging/main

        git push --set-upstream -f origin staging/main

        '
    - continue-on-error: true
      id: release
      name: Set Release Version
      run: "mvn -B versions:set versions:commit -DremoveSnapshot \necho \"version=$(mvn\
        \ -B help:evaluate -Dexpression=project.version -q -DforceStdout)\" >> $GITHUB_OUTPUT\n"
    - continue-on-error: true
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: staging/main
        commit_message: 'Prepare release (${{ github.actor }}): github-api-${{ steps.release.outputs.version
          }}'
        tagging_message: github-api-${{ steps.release.outputs.version }}
    - continue-on-error: true
      name: Increment Snapshot Version
      run: "mvn versions:set versions:commit -DnextSnapshot \n"
    - continue-on-error: true
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: staging/main
        commit_message: Prepare for next development iteration
    - continue-on-error: true
      name: pull-request to main
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: 'Prepare release (${{ github.actor }}): github-api-${{ steps.release.outputs.version
          }}'
        source_branch: staging/main
name: Create New Release Tag and PR
on:
  repository_dispatch:
    types: trigger-ga___create_release_tag_and_pr.yml
permissions:
  contents: write
  pull-requests: write
