env:
  JAVA_11_PLUS_MAVEN_OPTS: --add-opens jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
    --add-opens jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED
    --add-opens jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-opens jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
jobs:
  build:
    name: build-only (Java 17)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.JAVA_11_PLUS_MAVEN_OPTS }}
      name: Maven Install (skipTests)
      run: mvn -B clean install -DskipTests --file pom.xml
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: maven-target-directory
        path: target/
        retention-days: 3
    strategy:
      fail-fast: true
  site:
    name: site (Java 17)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.JAVA_11_PLUS_MAVEN_OPTS }}
      name: Maven Site
      run: mvn -B clean site -D enable-ci --file pom.xml
    strategy:
      fail-fast: false
  test:
    name: test (${{ matrix.os }}, Java ${{ matrix.java }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.JAVA_11_PLUS_MAVEN_OPTS }}
      if: matrix.os == 'windows'
      name: Maven Install without Code Coverage
      run: mvn -B clean install -D japicmp.skip=true --file pom.xml "-Dsurefire.argLine=--add-opens
        java.base/java.net=ALL-UNNAMED"
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.JAVA_11_PLUS_MAVEN_OPTS }}
      if: matrix.os != 'windows'
      name: Maven Install with Code Coverage
      run: mvn -B clean install -D enable-ci --file pom.xml "-Dsurefire.argLine=--add-opens
        java.base/java.net=ALL-UNNAMED"
    - continue-on-error: true
      if: matrix.os == 'ubuntu' && matrix.java == '17'
      name: Codecov Report
      uses: codecov/codecov-action@v4.1.1
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        - 17
        os:
        - ubuntu
        - windows
  test-java-8:
    name: test Java 8 (no-build)
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: maven-target-directory
        path: target
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Maven Test (no build) Java 8
      run: mvn -B surefire:test -DfailIfNoTests -Dsurefire.excludesFile=src/test/resources/slow-or-flaky-tests.txt
name: CI
on:
  repository_dispatch:
    types: trigger-ga___maven-build.yml
permissions:
  contents: read
