env:
  JAVA_11_PLUS_MAVEN_OPTS: --add-opens jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
    --add-opens jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED
    --add-opens jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-opens jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Maven Central Repository
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      env:
        MAVEN_OPTS: ${{ env.JAVA_11_PLUS_MAVEN_OPTS }}
      name: Maven Install and Site with Code Coverage
      run: mvn -B clean install site -D enable-ci --file pom.xml "-Dsurefire.argLine=--add-opens
        java.base/java.net=ALL-UNNAMED"
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: maven-release-target-directory
        path: target/
        retention-days: 3
  publish_gh_pages:
    if: ${{ github.ref == 'refs/heads/release/v1.x' }}
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: release
      name: Set Release Version
      run: 'echo "version=$(mvn -B help:evaluate -Dexpression=project.version -q -DforceStdout)"
        >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: maven-release-target-directory
        path: target
    - continue-on-error: true
      name: Checkout GH Pages
      run: 'git checkout -B gh-pages origin/gh-pages

        find . -type f -and -not -path ''./target/*'' -and -not -path ''./.*'' -and
        -not -name CNAME -delete

        cp -r ./target/site/* ./

        '
    - continue-on-error: true
      name: Publish GH Pages
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: gh-pages
        commit_message: 'Release (${{ github.actor }}): v${{ steps.release.outputs.version
          }}'
  publish_package:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Maven Central Repository
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        java-version: '17'
        server-id: sonatype-nexus-staging
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSPHRASE }}
        MAVEN_OPTS: ${{ env.JAVA_11_PLUS_MAVEN_OPTS }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_TOKEN_USERNAME }}
      name: Publish package
      run: mvn -B clean deploy -DskipTests -Prelease
name: Publish package to the Maven Central Repository
on:
  repository_dispatch:
    types: trigger-ga___publish_release_branch.yml
